### ISSUE TITLE
[Bug] Update available alerts / auto update broken when compose 'image' uses interpolation

### ISSUE THREAD

**Issue by mbecker20** [mbecker20/komodo#177]
For example the Komodo compose uses this:

```yaml
services:
  core:
    image: ghcr.io/mbecker20/komodo:${TAG:-latest}
```

which will not correctly find the latest image. It tries to find the image name BEFORE interpolation `ghcr.io/mbecker20/komodo:${TAG:-latest}`, which of course doesn't exist. It actually has to find the image name after interpolation. So instead of extracting from the compose yaml, the image name must be found another way.
