### ISSUE TITLE
Postgres connection not working

### ISSUE THREAD

**Issue by Cheezzhead** [mbecker20/komodo#182]
I had a working Komodo installation with Mongo a while back, and am now trying to run a fresh install using Ferretdb and Postgres. However I'm having some strange behavior.

- Even though the ferretdb connection seems to be working, no tables are created in the postgres database
- There is no error in the logs (that I can see) that indicates something is going wrong
- My user account that was stored in MongoDB **still works**, although I get the message 'user not enabled' when using those credentials.

All this occurs while the Komodo container can't physically access the mongo instance anymore (different bridge networks). However, when I start Komodo without Ferretdb, it (correctly) complains about this:

```
thread 'tokio-runtime-worker' panicked at bin/core/src/state.rs:46:6:
called `Result::unwrap()` on an `Err` value: failed to initialize database client

Caused by:
    failed to create index | index: enabled | error: Error { kind: ServerSelection { message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: ferretdb:27017, Type: Unknown, Error: Kind: I/O error: failed to lookup address information: Temporary failure in name resolution, labels: {} } ] }" }, labels: {}, wire_version: None, source: None }
```

I have no idea what is causing this, and I'm honestly scratching my head at the fact that my old credentials (from the mongoDB installation) are apparently still remembered by Komodo, at least in some way.

compose.yml:
```
services:
  komodo:
    image: ghcr.io/mbecker20/komodo:latest
    container_name: komodo
    # ...
    environment:
      KOMODO_HOST: https://komodo.${DOMAIN}
      #KOMODO_LOGGING_LEVEL: debug
      KOMODO_TITLE: ${ORGANISATION}
      KOMODO_FIRST_SERVER: http://periphery:8120
      KOMODO_DISABLE_CONFIRM_DIALOG: true
      ## Mongo
      #KOMODO_MONGO_ADDRESS: mongo:27017 # (Old mongo instance)
      KOMODO_DATABASE_URI: mongodb://komodo:${DB_PASSWORD}@ferretdb:27017/komodo?authMechanism=PLAIN
      ## Secrets
      KOMODO_PASSKEY: ${PASSKEY}
      KOMODO_WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      KOMODO_JWT_SECRET: ${JWT_SECRET}
      ## Auth
      KOMODO_LOCAL_AUTH: true
      KOMODO_ENABLE_NEW_USERS: true
      KOMODO_DISABLE_USER_REGISTRATION: false

  periphery:
    image: ghcr.io/mbecker20/periphery:latest
    container_name: periphery
    # ...
    volumes:
      - repo_cache:/repo-cache
      - ${DATA_DIR}/komodo/repos:/etc/komodo/repos
      - ${STACKS_DIR}:/etc/komodo/stacks
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PERIPHERY_PASSKEYS: ${PASSKEY}
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
  
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:latest
    container_name: ferretdb
    # ...
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://postgres:5432/komodo
```
