### ISSUE TITLE
[Documentation] Bind mounts when using `files_on_host` and a periphery container

### ISSUE THREAD

**Issue by otaconix** [mbecker20/komodo#196]
Hi, new Komodo user here. Thanks for making it, I'm enjoying it thus far!

First, some context: before Komodo, I would keep a directory with docker compose projects, and manually run `docker compose` commands over SSH whenever necessary. As I would like to still be able to do so, I'm using Komodo with stacks configured with `files_on_host = true`. 

A few of my stacks currently use Bind mounts. When I first redeployed such a stack, I was surprised to find the container fail to read whatever file I bind mounted. 

As it turns out, I'm running the periphery in a container with the host docker socket bind mounted, so the docker daemon interprets the relative paths in these Bind mounts from within the filesystem namespace of the host.

So, since the stack directory of a periphery installation defaults to `/etc/komodo/stacks/`, docker will create an empty directory in `/etc/komodo/stacks/<project_dir>/<relative_path>` and mount that. 

I solved my issue by setting the `stack_dir` to the same path as the directory containing my stacks on the host, and bind mount that stacks directory in the periphery container to an identical path. 

For reference, this is what it looks like:

```yaml
services:
  periphery:
    image: ghcr.io/mbecker20/periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    hostname: indium
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - default
    env_file: ./compose.env
    environment:
      KOMODO_STACK_DIR: /home/user/docker
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## manage repos in a docker volume, 
      ## or change it to an accessible host directory.
      - repos:/etc/komodo/repos
      ## manage stack files in a docker volume, 
      ## or change it to an accessible host directory.
      - /home/user/docker:/home/user/docker
```

I probably won't be the last person running into this issue, so I thought I'd submit an issue to request something like this to be documented. Perhaps under the following section?: https://komo.do/docs/deploy-containers/configuration#configuring-volumes
