### ISSUE TITLE
[bug] service with  "-" in name not detected

### ISSUE THREAD

**Issue by ValgulNecron** [mbecker20/komodo#211]
so if i have a compose 
```yml
name: it-tools

networks:
  traefik:
    external: true

services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    restart: unless-stopped
    container_name: it-tools
    hostname: it-tools
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.ittools.rule: Host(`it-tools.exemple.com`)
      traefik.http.routers.ittools.entrypoints: websecure
      traefik.http.services.ittools.loadbalancer.server.port: 80
      traefik.http.routers.ittools.service: it-tools
```

and if go into the stack
![image](https://github.com/user-attachments/assets/cb3568a8-7ca4-48b4-964b-6de77388f80b)

but if i go in containers
![image](https://github.com/user-attachments/assets/ab047717-0009-475d-af4e-d65af0086aa6)

it is detected and shown
