### ISSUE TITLE
unknown flag: --format while deploying a stack

### ISSUE THREAD

**Issue by stamonty** [mbecker20/komodo#236]
First of all I would like to thank you for the great software!
I was able to to successfully migrate a couple of stacks from Portainer to Komodo exept Immich.

On compose build step I got `unknown flag: --format`:
![immich error](https://github.com/user-attachments/assets/d3a098e7-b91f-47c0-8042-802cf38d16e5)

Haven't seen `config --format json` while deploying other stacks.
I assume second `--env-file` was mistakenly added.

Also I've tried to reuse Komodo demo immich stack configuration. Got exactly the same error. 
Peripheral agent is deployed as docker container.

BTW, `environment written to "/etc/komodo/stacks/immich/.env"`
No actual file was created. Is it expected behavior? Same goes for other stacks, though deployment went successful.

Docmost stack deployment for comparison
![docmost](https://github.com/user-attachments/assets/e5b04640-8823-41e0-b2ea-0a4cd9f37f24)

Just let me know if I could help to track the issue by providing any additional information needed.

**Comment by mbecker20** [comment]
It looks like and additional env file is not being passed. the command has:

`--env-file .env --env-file config --format json`.

Maybe you added an additional env file, but left it blank? If this isn't it, please share you resource TOML.

**Comment by stamonty** [comment]
Many thanks! 
>Maybe you added an additional env file, but left it blank
It is exactly what've happened!
Assume it would be better not to save an empty envs or at least ignore them while deploying.
Issue was so trivial but I was completely sure that an empty state wasn't saved that didn't bother to double checked.

**Comment by stamonty** [comment]
> BTW, environment written to "/etc/komodo/stacks/immich/.env"
No actual .env file was created. Is it expected behavior? Same goes for other stacks, though deployment went successful and env vars have been passed to containers.

Also, if possible, could you please elaborate on that.

**Comment by mbecker20** [comment]
Can you check `ls -a` and see if you see it? Its possible you just don't see it because usually paths starting with `.` are hidden.

**Comment by stamonty** [comment]
Sure, hear it goes:

```
/etc/komodo/stacks/immich$ ls -a
.  ..  library  postgres

```
No env for immich stack

```
:/etc/komodo/stacks$ ls -a
.  ..  immich

```
Same for Docmost (even directory was not created)

**Comment by mbecker20** [comment]
Its strange to not see the compose file in there either. I am assuming you mount `/etc/komodo/stacks:/etc/komodo/stacks` to Periphery container? This should be correct.

Could you share:
1. Your Periphery compose service / docker run command (how you launch Periphery)
2. Your resource TOML (navigate to the stack and use the TOML button)

**Comment by stamonty** [comment]
How Periphery agent starts:
`docker compose -p komodo -f komodo.yaml --env-file komodo.env up -d`

Both files are located outside /etc

komodo.yaml

```
services:
  periphery:
    container_name: komodo_agent
    image: ghcr.io/mbecker20/periphery:latest
    # image: ghcr.io/mbecker20/periphery:latest-aarch64 # use for arm support
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    ports:
      - 8120:8120
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## use self signed certs in docker volume,
      ## or mount your own signed certs.
      - ssl-certs:/etc/komodo/ssl
      ## manage repos in a docker volume,
      ## or change it to an accessible host directory.
      - repos:/etc/komodo/repos
      ## manage stack files in a docker volume,
      ## or change it to an accessible host directory.
      - stacks:/etc/komodo/stacks
      ## Optionally mount a path to store compose files
      # - /path/to/compose:/host/compose
    env_file: komodo.env
    environment:
      ## Full list: `https://github.com/mbecker20/komodo/blob/main/config/periphery.config.toml`
      ## Configure the same passkey given to Komodo Core (KOMODO_PASSKEY)
      PERIPHERY_PASSKEYS: ${PERIPHERY_PASSKEYS} # Alt: PERIPHERY_PASSKEYS_FILE
      ## Adding IP here will ensure calling IP is in the list. (optional)
      PERIPHERY_ALLOWED_IPS:
      ## Enable HTTPS server
      PERIPHERY_SSL_ENABLED: true
      ## If the disk size is overreporting, can use one of these to
      ## whitelist / blacklist the disks to filter them, whichever is easier.
      ## Accepts comma separated list of paths.
      ## Usually whitelisting /etc/hostname gives correct size.
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      # PERIPHERY_EXCLUDE_DISK_MOUNTS: /snap,/etc/repos

volumes:
  ssl-certs:
  repos:
  stacks:

```
komodo.env
`PERIPHERY_PASSKEYS=`


PERIPHERY CONTAINER LOG
```
2024-12-21T20:15:05.801590729Z 2024-12-21T20:15:05.801534Z  INFO periphery: Komodo Periphery version: v1.16.12
2024-12-21T20:15:05.802620299Z 2024-12-21T20:15:05.801629Z  INFO periphery: PeripheryConfig { port: 8120, repo_dir: "/etc/komodo/repos", stack_dir: "/etc/komodo/stacks", stats_polling_rate: FiveSeconds, legacy_compose_cli: false, logging: LogConfig { level: Info, stdio: Standard, otlp_endpoint: "", opentelemetry_service_name: "Komodo" }, allowed_ips: [], passkeys: ["##############"], include_disk_mounts: ["/etc/hostname"], exclude_disk_mounts: [], secrets: {}, git_providers: [], docker_registries: [], ssl_enabled: true, ssl_key_file: "/etc/komodo/ssl/key.pem", ssl_cert_file: "/etc/komodo/ssl/cert.pem" }
2024-12-21T20:15:05.809239737Z 2024-12-21T20:15:05.804176Z  INFO periphery: 🔒 Periphery SSL Enabled
```
