### ISSUE TITLE
[Feature] Create networks through the UI

### ISSUE THREAD

**Issue by cantchooseaname8** [mbecker20/komodo#57]
It would be a huge help to be able to set up new networks (macvlan, ipvlan, bridge) through the Komodo UI. I have a few containers on a macvlan so I can route the traffic accordingly through my firewall. This is the one thing that keeps me using Portainer. Managing the networks via cli is something that has always been way over my head, so doing it through the UI would be a huge help.

**Comment by Wikibear** [comment]
Would be nice to get this feature like Portainer.

**Comment by undefinedid** [comment]
+1, creating/deleting networks and volumes would be a really great feature in order to completely replace Portainer!

**Comment by jlbnetwork** [comment]
And I would add: not only creating/deleting networks... But having a place to see which networks exist and browse them, like you can browse your stacks and your servers.

**Comment by mbecker20** [comment]
@jlbnetwork You can already browse networks and easy access to pruning unused networks, see the Server page, under the `Docker` tab.

**Comment by jlbnetwork** [comment]
> [@jlbnetwork](https://github.com/jlbnetwork) You can already browse networks and easy access to pruning unused networks, see the Server page, under the `Docker` tab.

Omg, you're so right. I totally missed this. Thank you!

**Comment by hilsonp** [comment]
Just came here to say that I was just looking for the same:
Be able to add a network from the Komodo interface ☺️

**Comment by Mannshoch** [comment]
If possible, please add a possibillity to cut internet acces or limit acces to a certain network.

Most of my Container do not need internet access but they have it cause im not able to lock it without locking the sysyem where docker runs on it.

**Comment by kiler129** [comment]
@Mannshoch I think this would be very out of scope for Komodo. Use standard firewalling facilities in `DOCKER-USER` chain to modify egress rules.

**Comment by Mannshoch** [comment]
That's surprising. Why is it out of scope?

**Comment by kiler129** [comment]
@Mannshoch Docker deliberately doesn't provide any API to manage firewall. IMO Komodo manages Docker Engine and not the underlying OS. In other words, there's a boundary defined by Docker authors. For example Kubernetus defines it differently, and includes network policies management in the stack.

Moreover, making a good firewall for a Docker host is a bit of a minefield, given how it uses NAT, and how it interacts with other networks drivers. In practice, to do it correctly you need to disable default bridge, implement deny-all policy, and add your own network(s) with rules you design.
After spending a good 4 days on the problem, I can say with just a little bit of confidence that the problem only looks simple ;)

**Comment by Mannshoch** [comment]
Thanks for investigating here. 

I meanwhile asked a coworker in our IT and he told me that if I create a new network in Docker this normally do not have internet access because it lacks the gateway setting, he never used it but it should work. I will test it that way.

I hope you will find a good network developer that is willing to deep dive into that and create a usable firewall.

While searching around, I come more and more to conclusion, that fire-walling and control internet access is surprising difficult. Our IT praised their expensive all in one solution that does the job within the company.

**Comment by psychowood** [comment]
@Mannshoch If you just want to isolate a stack you can define a network with `internal:true` and it will be isolated. Beware that you can't expose ports that way, you need to use a reverse proxy (as you should anyway :) ).

**Comment by Mannshoch** [comment]
No, the goal is simply that my selfhosted apps should not connect to Internet but be accessible in my LAN. I currently do not have any selfhosted server apps that have a need for permanent Internet access. I have two which need only temporary access for certain maintainance.

**Comment by DoPri** [comment]
@Mannshoch, what psychowood wrote should fit your use case. As you can see [here](https://docs.docker.com/reference/cli/docker/network/create/#internal), the `internal` flag ensures that containers within the network cannot communicate with any networks (i.e., not the Internet) other than other containers within the same internal network. As your colleague explained, this is due to the lack of gateway configuration (and the firewall rules set by Docker). So this should be exactly what you need.

---

To add my 2 cents to the issue itself: I also think that network management similar to Portainer is a very useful/desirable and, for me, important feature.

**Comment by psychowood** [comment]
@Mannshoch adding my two cents, if you want LAN only access you can also look for macvlan networks, adding the reverse proxy to your lan subnet with a defined IP, possibly mapped at router level with a static domain name. 
Something like this (*this is just an example* but my traefik configuration is like this.

```yaml
services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
# No need to expose ports since you'd access via lan ip address
#    ports:
#      - "80:80"
#      - "443:443"
    networks:
      lan:
        ipv4_address: 192.168.1.70
      reverse-proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  internal-app:
    image: traefik/whoami
    container_name: internal-app
    networks:
      - reverse-proxy

networks:
  lan:
    name: mylan
    driver: lan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.64/26

  reverse-proxy:
    name: reverse-proxy
    internal: true
```

Jumping back in topic, imho:
- creating new networks via UI is just a nice-to-have feature (my approach is having a git repo with a docker-compose stack where all the system-wise networks are created, I can deploy it when I want, perhaps with a single system wise service like komodo itself or a dummy service)
- a connect/disconnect facility inside a single service would be much more useful, moreover with a flag that automatically updates the stack compose file to make that connection/disconnection permanent
- a visual representation of the network graph (I'm currently using edgeshark for this) would be niiiiice, too.

I could wrap a PR if any of this is considered useful by @mbecker20
