### ISSUE TITLE
[Bug] In "Stack": "latest contents" does not update when switching to "Files on Server"

### ISSUE THREAD

**Issue by mmartial** [mbecker20/komodo#67]
Using the tool with bind mount to edit configuration files or create required directories.

Steps to reproduce:
- In `Stack`: create a new stack
- Enter the `compose.yaml` in the UI
- `Deploy` the stack
- `Stop` the stack
- (optional) manually create the configuration/directories for that stack in the stack directory created in the bind mount for /etc/komodo/stacks
- Manually modified the `compose.yaml` file in that directory to reflect the added files
- From the stopped stack, switch to `Files on Server`
- Re-`start` the stack

When checking the "stack" "info" tab, the `latest contents:` still shows the original `compose.yaml` entered via the UI, not the modified one.

Expected behavior: `Files on Server` should have `latest contents:` display the local `compose.yaml` file

**Comment by mbecker20** [comment]
The was a frontend bug that always shows UI defined contents as "latest" if they exist. That behavior doesn't work since the newer `Files on Host` mode was added. Fix is in, will be included in 1.14.1 releasing soon

**Comment by mbecker20** [comment]
The fix is out now: [https://github.com/mbecker20/komodo/releases/tag/v1.14.1](https://github.com/mbecker20/komodo/releases/tag/v1.14.1). Thanks for letting me know!

**Comment by mbecker20** [comment]
When you can, could you check this works for you and we can close the issue?

**Comment by mmartial** [comment]
I tested, but I do not believe it works. The UI reflects the right content, but the started container has the previous `compose.yaml`.

How to test:
- Create a new stack
- Add a compose.yaml file
```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 33009:3000 # changing the default exposed port to 33009
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    command:
      - sleep 5; exit 1
```
- `Deploy` wait for it to fail
- manually edit the `compose.yaml` to remove the `command:` entry
- Switch to `files on server` 
- check the `info` tab, which will show the updated file
- click `start` (not `redeploy`)
- The container fails with an error message related to the deleted `command:` section (i.e., it still uses the older `compose.yaml`?)

Side note: the stack has to be `deployed` before we can populate the directory with the required sidecar files (here a `config` directory); it would be good to have a `create stack` option that could be used before a `deploy`
