### ISSUE TITLE
[Bug] relative bind mounts in stacks are deleted after deployment

### ISSUE THREAD

**Issue by yyogo** [mbecker20/komodo#68]
The root stack directory in `komodo/stacks` is deleted immediately after deployment. This causes issues when a `docker-compose.yaml` contains relative bind mounts. e.g, in this compose `test_relative` fails after deployment:

```yaml
services:
  test_relative:
    image: alpine:latest
    command: sh -c "sleep 5 &&  echo hello > /test/hello && echo success"
    volumes:
      - ./test:/test
  test_absolute:
    image: alpine:latest
    command: sh -c "sleep 5 &&  echo hello > /test/hello && echo success"
    volumes:
      - /tmp/test_komodo_bug:/test
```
