### ISSUE TITLE
Deployment / Stack can edit config files, and write them just before deploy time for mounting to containers

### ISSUE THREAD

**Issue by mbecker20** [mbecker20/komodo#92]
With a better UI editor for config files, this will be nice.

`Deployment.config_file: Array<{ path: string; content: string;  }>`

The Example Resource Toml:
```toml
[[deployment]]
name = "example"
config.image.type = "Image"
config.image.params.image = "caddy"
config.network = "host"
config.volumes = "/configs/example/Caddyfile:/etc/caddy/Caddyfile"
[[deployment.config_file]]
path = "/configs/example/Caddyfile"
content = """
site.domain {
   reverse_proxy localhost:9120
}
"""
```

I don't love the long absolute path to the
